#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Dec 25 22:58:06 CET 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Sildur's+Enhanced+Default+v1.15+Fancy.zip
